variables:
    PLUGIN_NAME: 'selectionOfReviewingInterests'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_3_0
    file:
      - 'templates/groups/pkp_plugin.yml'